#!/usr/bin/env bash
# Update index and if changed reload it in the server

BASEDIR="/var/www/mognet"
HASH=`cksum < $BASEDIR/data/index.json`
$BASEDIR/app/bin/update.js >/dev/null
NEW_HASH=`cksum < $BASEDIR/data/index.json`
if [ ! -e $BASEDIR/app/server.pid ]; then
    exit 0
fi
if [ "$NEW_HASH" != "$HASH" ]; then
    kill -HUP `cat $BASEDIR/app/server.pid`
else
    echo "No need to reload"
fi
